version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/BE
    overwrite: yes

permissions:
  - object: /
    pattern: "*"
    owner: ubuntu
    group: ubuntu

hooks:
#  Install:
#    - location: scripts/install.sh
#      timeout: 120
#      runas: root

  AfterInstall:
    - location: scripts/stop.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu